<a href="https://colab.research.google.com/github/Muhammad-Waleed-Source/Machine-Learning/blob/main/Day-28/Column-transformer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd

In [1]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [3]:
df = pd.read_csv('covid_toy.csv')

In [4]:
df.head()

,age,gender,fever,cough,city,has_covid
0,60,Male,103.0,Mild,Kolkata,No
1,27,Male,100.0,Mild,Delhi,Yes
2,42,Male,101.0,Mild,Delhi,No
3,31,Female,98.0,Mild,Kolkata,No
4,65,Female,101.0,Mild,Mumbai,No


In [8]:
df['cough'].value_counts()

,count
cough,
Mild,62
Strong,38


In [10]:
df['city'].value_counts()

,count
city,
Kolkata,32
Bangalore,30
Delhi,22
Mumbai,16


In [7]:
df.isnull().sum()

# fever col has 10 missing values

,0
age,0
gender,0
fever,10
cough,0
city,0
has_covid,0


In [11]:
from sklearn.model_selection import train_test_split

In [12]:
X_train, X_test, y_train, y_test = train_test_split(df.drop(columns=['has_covid']), df['has_covid'], test_size=0.2, random_state=2)

In [13]:
X_train.head()

,age,gender,fever,cough,city
35,82,Female,102.0,Strong,Bangalore
11,65,Female,98.0,Mild,Mumbai
84,69,Female,98.0,Strong,Mumbai
44,20,Male,102.0,Strong,Delhi
73,34,Male,98.0,Strong,Kolkata


In [14]:
X_test.head()

,age,gender,fever,cough,city
83,17,Female,104.0,Mild,Kolkata
30,15,Male,101.0,Mild,Delhi
56,71,Male,NaN,Strong,Kolkata
24,13,Female,100.0,Strong,Kolkata
16,69,Female,103.0,Mild,Kolkata


# 1. Without ColumnTransformer

### Simple imputer for fever col

In [16]:
# adding simple imputer to fever col
si = SimpleImputer()

X_train_fever = si.fit_transform(X_train[['fever']])

# also the test data
X_test_fever = si.fit_transform(X_test[['fever']])

X_train_fever

array([[102.        ],
       [ 98.        ],
       [ 98.        ],
       [102.        ],
       [ 98.        ],
       [100.79166667],
       [100.79166667],
       [101.        ],
       [104.        ],
       [104.        ],
       [102.        ],
       [100.        ],
       [ 98.        ],
       [ 99.        ],
       [101.        ],
       [100.        ],
       [101.        ],
       [103.        ],
       [100.79166667],
       [100.79166667],
       [ 99.        ],
       [ 98.        ],
       [101.        ],
       [ 99.        ],
       [104.        ],
       [101.        ],
       [100.79166667],
       [100.        ],
       [102.        ],
       [101.        ],
       [101.        ],
       [101.        ],
       [ 98.        ],
       [104.        ],
       [ 99.        ],
       [100.79166667],
       [104.        ],
       [ 99.        ],
       [101.        ],
       [100.        ],
       [104.        ],
       [100.79166667],
       [ 99.        ],
       [ 98

In [17]:
X_train_fever.shape

(80, 1)

### OrdinalEncoding for cough col

In [19]:
oe = OrdinalEncoder(categories=[['Mild', 'Strong']])

X_train_cough = oe.fit_transform(X_train[['cough']])

# also the test data
X_test_cough = oe.fit_transform(X_test[['cough']])

X_train_cough

array([[1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],

In [20]:
X_train_cough.shape

(80, 1)

### OneHotEncoding on gender and city cols

In [22]:
df['gender'].value_counts()

,count
gender,
Female,59
Male,41


In [24]:
df['city'].value_counts()

,count
city,
Kolkata,32
Bangalore,30
Delhi,22
Mumbai,16


In [26]:
ohe = OneHotEncoder(drop='first', sparse_output=False)

X_train_gender_city = ohe.fit_transform(X_train[['gender', 'city']])

# also the test data
X_test_gender_city = ohe.fit_transform(X_test[['gender', 'city']])

X_train_gender_city

array([[0., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [1., 1., 0., 0.],
       [1., 0., 1., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [1., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.],
       [1., 0., 1., 0.],
       [1., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],


In [27]:
X_train_gender_city.shape

(80, 4)

Now concatinating all of them.

In [29]:
# extracting age
X_train_age = X_train.drop(columns=['gender', 'fever', 'cough', 'city']).values

# also the test data
X_test_age = X_test.drop(columns=['gender', 'fever', 'cough', 'city']).values

X_train_age

array([[82],
       [65],
       [69],
       [20],
       [34],
       [84],
       [23],
       [ 8],
       [34],
       [56],
       [69],
       [27],
       [64],
       [66],
       [38],
       [11],
       [14],
       [46],
       [38],
       [75],
       [25],
       [83],
       [47],
       [60],
       [12],
       [34],
       [42],
       [19],
       [24],
       [81],
       [64],
       [51],
       [40],
       [ 6],
       [49],
       [82],
       [42],
       [72],
       [20],
       [19],
       [75],
       [79],
       [59],
       [ 5],
       [25],
       [14],
       [19],
       [47],
       [51],
       [ 5],
       [68],
       [19],
       [54],
       [73],
       [65],
       [23],
       [26],
       [49],
       [11],
       [27],
       [65],
       [65],
       [50],
       [55],
       [12],
       [83],
       [10],
       [18],
       [16],
       [27],
       [44],
       [74],
       [20],
       [ 5],
       [24],
       [22],
       [71],

In [30]:
X_train_age.shape

(80, 1)

In [32]:
# now concatinating

X_trained_transformed = np.concatenate((X_train_age, X_train_fever, X_train_gender_city, X_train_cough), axis=1)

# also the test data
X_test_transformed = np.concatenate((X_test_age, X_test_fever, X_test_gender_city, X_test_cough), axis=1)

X_trained_transformed

array([[ 82.        , 102.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   1.        ],
       [ 65.        ,  98.        ,   0.        ,   0.        ,
          0.        ,   1.        ,   0.        ],
       [ 69.        ,  98.        ,   0.        ,   0.        ,
          0.        ,   1.        ,   1.        ],
       [ 20.        , 102.        ,   1.        ,   1.        ,
          0.        ,   0.        ,   1.        ],
       [ 34.        ,  98.        ,   1.        ,   0.        ,
          1.        ,   0.        ,   1.        ],
       [ 84.        , 100.79166667,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [ 23.        , 100.79166667,   1.        ,   0.        ,
          0.        ,   1.        ,   0.        ],
       [  8.        , 101.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 34.        , 104.        ,   0.        ,   1.        ,
          0.    

In [33]:
X_trained_transformed.shape

(80, 7)